/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/produit.glb --types --output src/components/canvas/Produit.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    group1022724333_1: THREE.Mesh
    group1022724333_2: THREE.Mesh
    group1022724333_3: THREE.Mesh
    group629861773_1: THREE.Mesh
    group629861773_2: THREE.Mesh
    group629861773_3: THREE.Mesh
    group1582119280_1: THREE.Mesh
    group1582119280_2: THREE.Mesh
    group1582119280_3: THREE.Mesh
    group438901791_1: THREE.Mesh
    group438901791_2: THREE.Mesh
    group1399775543_1: THREE.Mesh
    group1399775543_2: THREE.Mesh
    group594643087_1: THREE.Mesh
    group594643087_2: THREE.Mesh
    group594643087_3: THREE.Mesh
    Screwdriver_1: THREE.Mesh
    Screwdriver_2: THREE.Mesh
    group1416475030_1: THREE.Mesh
    group1416475030_2: THREE.Mesh
    group1416475030_3: THREE.Mesh
    group931417814_1: THREE.Mesh
    group931417814_2: THREE.Mesh
    group931417814_3: THREE.Mesh
    group1677974325_1: THREE.Mesh
    group1677974325_2: THREE.Mesh
    group1503477721: THREE.Mesh
    group1500111175: THREE.Mesh
    group1903879849_1: THREE.Mesh
    group1903879849_2: THREE.Mesh
    group348818362_1: THREE.Mesh
    group348818362_2: THREE.Mesh
    group1115598653_1: THREE.Mesh
    group1115598653_2: THREE.Mesh
    Paint_Brush_1: THREE.Mesh
    Paint_Brush_2: THREE.Mesh
    Paint_Brush_3: THREE.Mesh
    Paint_Brush_4: THREE.Mesh
    Paint_Brush_5: THREE.Mesh
    Paint_Brush_6: THREE.Mesh
    Hand_Saw_1: THREE.Mesh
    Hand_Saw_2: THREE.Mesh
    group634296461_1: THREE.Mesh
    group634296461_2: THREE.Mesh
    Pliers_1: THREE.Mesh
    Pliers_2: THREE.Mesh
    Pliers_3: THREE.Mesh
    Paint_Brush001_1: THREE.Mesh
    Paint_Brush001_2: THREE.Mesh
    Paint_Brush001_3: THREE.Mesh
    Paint_Brush001_4: THREE.Mesh
    Bench_1: THREE.Mesh
    Bench_2: THREE.Mesh
    Bench_3: THREE.Mesh
    Bench_4: THREE.Mesh
    Bench_5: THREE.Mesh
    Bench_6: THREE.Mesh
    group1673330486063: THREE.Mesh
    group1673330486080: THREE.Mesh
    Vice_Clamp_1: THREE.Mesh
    Vice_Clamp_2: THREE.Mesh
    group1673330486103_1: THREE.Mesh
    group1673330486103_2: THREE.Mesh
    Glue_1: THREE.Mesh
    Glue_2: THREE.Mesh
    Glue_3: THREE.Mesh
  }
  materials: {
    mat19: THREE.MeshStandardMaterial
    mat13: THREE.MeshStandardMaterial
    mat15: THREE.MeshStandardMaterial
    mat8: THREE.MeshStandardMaterial
    mat23: THREE.MeshStandardMaterial
    mat9: THREE.MeshStandardMaterial
    mat5: THREE.MeshStandardMaterial
    mat16: THREE.MeshStandardMaterial
    mat17: THREE.MeshStandardMaterial
    mat14: THREE.MeshStandardMaterial
    mat12: THREE.MeshStandardMaterial
    mat24: THREE.MeshStandardMaterial
    mat18: THREE.MeshStandardMaterial
    mat20: THREE.MeshStandardMaterial
    mat21: THREE.MeshStandardMaterial
    mat3: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/produit.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={100}>
        <mesh geometry={nodes.group1022724333_1.geometry} material={materials.mat19} />
        <mesh geometry={nodes.group1022724333_2.geometry} material={materials.mat13} />
        <mesh geometry={nodes.group1022724333_3.geometry} material={materials.mat15} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group629861773_1.geometry} material={materials.mat19} />
        <mesh geometry={nodes.group629861773_2.geometry} material={materials.mat13} />
        <mesh geometry={nodes.group629861773_3.geometry} material={materials.mat15} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group1582119280_1.geometry} material={materials.mat19} />
        <mesh geometry={nodes.group1582119280_2.geometry} material={materials.mat13} />
        <mesh geometry={nodes.group1582119280_3.geometry} material={materials.mat15} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group438901791_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.group438901791_2.geometry} material={materials.mat8} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group1399775543_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.group1399775543_2.geometry} material={materials.mat8} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group594643087_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.group594643087_2.geometry} material={materials.mat8} />
        <mesh geometry={nodes.group594643087_3.geometry} material={materials.mat23} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.Screwdriver_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.Screwdriver_2.geometry} material={materials.mat8} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group1416475030_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.group1416475030_2.geometry} material={materials.mat9} />
        <mesh geometry={nodes.group1416475030_3.geometry} material={materials.mat5} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group931417814_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.group931417814_2.geometry} material={materials.mat16} />
        <mesh geometry={nodes.group931417814_3.geometry} material={materials.mat17} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group1677974325_1.geometry} material={materials.mat17} />
        <mesh geometry={nodes.group1677974325_2.geometry} material={materials.mat14} />
      </group>
      <mesh geometry={nodes.group1503477721.geometry} material={materials.mat12} scale={100} />
      <mesh geometry={nodes.group1500111175.geometry} material={materials.mat12} scale={100} />
      <group scale={100}>
        <mesh geometry={nodes.group1903879849_1.geometry} material={materials.mat17} />
        <mesh geometry={nodes.group1903879849_2.geometry} material={materials.mat14} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group348818362_1.geometry} material={materials.mat13} />
        <mesh geometry={nodes.group348818362_2.geometry} material={materials.mat14} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group1115598653_1.geometry} material={materials.mat23} />
        <mesh geometry={nodes.group1115598653_2.geometry} material={materials.mat24} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.Paint_Brush_1.geometry} material={materials.mat19} />
        <mesh geometry={nodes.Paint_Brush_2.geometry} material={materials.mat15} />
        <mesh geometry={nodes.Paint_Brush_3.geometry} material={materials.mat23} />
        <mesh geometry={nodes.Paint_Brush_4.geometry} material={materials.mat16} />
        <mesh geometry={nodes.Paint_Brush_5.geometry} material={materials.mat18} />
        <mesh geometry={nodes.Paint_Brush_6.geometry} material={materials.mat20} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.Hand_Saw_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.Hand_Saw_2.geometry} material={materials.mat20} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group634296461_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.group634296461_2.geometry} material={materials.mat20} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.Pliers_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.Pliers_2.geometry} material={materials.mat5} />
        <mesh geometry={nodes.Pliers_3.geometry} material={materials.mat16} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.Paint_Brush001_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.Paint_Brush001_2.geometry} material={materials.mat23} />
        <mesh geometry={nodes.Paint_Brush001_3.geometry} material={materials.mat16} />
        <mesh geometry={nodes.Paint_Brush001_4.geometry} material={materials.mat18} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.Bench_1.geometry} material={materials.mat19} />
        <mesh geometry={nodes.Bench_2.geometry} material={materials.mat15} />
        <mesh geometry={nodes.Bench_3.geometry} material={materials.mat23} />
        <mesh geometry={nodes.Bench_4.geometry} material={materials.mat17} />
        <mesh geometry={nodes.Bench_5.geometry} material={materials.mat18} />
        <mesh geometry={nodes.Bench_6.geometry} material={materials.mat21} />
      </group>
      <mesh geometry={nodes.group1673330486063.geometry} material={materials.mat15} scale={100} />
      <mesh geometry={nodes.group1673330486080.geometry} material={materials.mat23} scale={100} />
      <group scale={100}>
        <mesh geometry={nodes.Vice_Clamp_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.Vice_Clamp_2.geometry} material={materials.mat8} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.group1673330486103_1.geometry} material={materials.mat14} />
        <mesh geometry={nodes.group1673330486103_2.geometry} material={materials.mat18} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes.Glue_1.geometry} material={materials.mat15} />
        <mesh geometry={nodes.Glue_2.geometry} material={materials.mat21} />
        <mesh geometry={nodes.Glue_3.geometry} material={materials.mat3} />
      </group>
    </group>
  )
}

useGLTF.preload('/produit.glb')

export default Model
